version: "3.9"
   
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
    volumes:
      - .:/code
      - ./static:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - cache

volumes:
  cache:
    driver: local
